[package]
name = "compute"
version = "0.1.15"
authors = ["Jeff Shen <jshen2014@hotmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

readme = "README.md"
description = "A crate for statistical computing."
repository = "https://github.com/al-jshen/compute"

categories = ["science"]
keywords = ["statistics", "compute", "data"]

[dependencies]
fastrand = "1"
approx_eq = "0.1"
blas = "0.20"
lapack = "0.16"
openblas-src = "0.9"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark_summary"
harness = false

[[bench]]
name = "benchmark_distributions"
harness = false

[[bench]]
name = "benchmark_functions"
harness = false

[[bench]]
name = "benchmark_timeseries"
harness = false
