[package]
name = "gp_regression"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compute = "0.1.31"
plotly = "0.6"
